# Site settings
title: HICKORY CREEK | MADE IN ALABAMA
email: tgray.it@gmail.com
description: ""
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://hickorycreek.co" # the base hostname & protocol for your site
twitter_username: jtgry
github_username:  jtgry

# Build settings
markdown: kramdown


collections:
  products:
    output: true
    permalink: /products/:path/
